[package]
name = "git-recap"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi-to-tui = "8.0.1"
chrono = "0.4.45"
crossterm = "0.29.0"
fuzzy-matcher = "0.3.7"
git2 = "0.21.0"
ratatui = "0.30.2"
rayon = "1.12.0"
reqwest = { version = "0.13.4", features = ["blocking", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tui-input = "0.15.3"
walkdir = "2.5.0"
